import { AircraftCategory, Flight, Gate, GroundVehicle, Runway, WeatherState } from '../types';

export const INITIAL_RUNWAYS: Runway[] = [
  {
    id: '09L/27R',
    name: 'RWY 09L/27R',
    headingPrimary: '09L',
    headingReciprocal: '27R',
    activeHeading: '09L',
    lengthFt: 11500,
    status: 'ACTIVE',
    ilsCategory: 'CAT IIIb',
    visualRangeRVR: 1400,
    coordinates: {
      start: { x: 100, y: 130 },
      end: { x: 880, y: 130 },
      thresholdHeading: 90,
    },
  },
  {
    id: '09R/27L',
    name: 'RWY 09R/27L',
    headingPrimary: '09R',
    headingReciprocal: '27L',
    activeHeading: '09R',
    lengthFt: 10800,
    status: 'ACTIVE',
    ilsCategory: 'CAT II',
    visualRangeRVR: 1200,
    coordinates: {
      start: { x: 120, y: 530 },
      end: { x: 900, y: 530 },
      thresholdHeading: 90,
    },
  },
  {
    id: '18/36',
    name: 'RWY 18/36',
    headingPrimary: '18',
    headingReciprocal: '36',
    activeHeading: '18',
    lengthFt: 8600,
    status: 'ACTIVE',
    ilsCategory: 'CAT I',
    visualRangeRVR: 2000,
    coordinates: {
      start: { x: 330, y: 60 },
      end: { x: 330, y: 580 },
      thresholdHeading: 180,
    },
  },
];

// 22 Gates across Concourse A, B, C
export const INITIAL_GATES: Gate[] = [
  // Concourse A (Gates A1 - A8)
  {
    id: 'A1',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 390, y: 250, angle: 90 },
    pushbackCoords: { x: 390, y: 220 },
  },
  {
    id: 'A2',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 440, y: 250, angle: 90 },
    pushbackCoords: { x: 440, y: 220 },
  },
  {
    id: 'A3',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 490, y: 250, angle: 90 },
    pushbackCoords: { x: 490, y: 220 },
  },
  {
    id: 'A4',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'OCCUPIED',
    hasDualJetbridge: false,
    coordinates: { x: 540, y: 250, angle: 90 },
    pushbackCoords: { x: 540, y: 220 },
  },
  {
    id: 'A5',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 590, y: 250, angle: 90 },
    pushbackCoords: { x: 590, y: 220 },
  },
  {
    id: 'A6',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'OCCUPIED',
    hasDualJetbridge: false,
    coordinates: { x: 640, y: 250, angle: 90 },
    pushbackCoords: { x: 640, y: 220 },
  },
  {
    id: 'A7',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'OCCUPIED',
    hasDualJetbridge: true,
    coordinates: { x: 700, y: 250, angle: 90 },
    pushbackCoords: { x: 700, y: 215 },
  },
  {
    id: 'A8',
    concourse: 'A',
    terminal: 'T1',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'AVAILABLE',
    hasDualJetbridge: true,
    coordinates: { x: 760, y: 250, angle: 90 },
    pushbackCoords: { x: 760, y: 215 },
  },

  // Concourse B (Gates B1 - B8)
  {
    id: 'B1',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 390, y: 340, angle: 90 },
    pushbackCoords: { x: 390, y: 310 },
  },
  {
    id: 'B2',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'OCCUPIED',
    hasDualJetbridge: false,
    coordinates: { x: 440, y: 340, angle: 90 },
    pushbackCoords: { x: 440, y: 310 },
  },
  {
    id: 'B3',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 490, y: 340, angle: 90 },
    pushbackCoords: { x: 490, y: 310 },
  },
  {
    id: 'B4',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'D',
    allowedCategories: ['C', 'D'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 540, y: 340, angle: 90 },
    pushbackCoords: { x: 540, y: 310 },
  },
  {
    id: 'B5',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'OCCUPIED',
    hasDualJetbridge: false,
    coordinates: { x: 590, y: 340, angle: 90 },
    pushbackCoords: { x: 590, y: 310 },
  },
  {
    id: 'B6',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'OCCUPIED',
    hasDualJetbridge: true,
    coordinates: { x: 650, y: 340, angle: 90 },
    pushbackCoords: { x: 650, y: 305 },
  },
  {
    id: 'B7',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'AVAILABLE',
    hasDualJetbridge: true,
    coordinates: { x: 710, y: 340, angle: 90 },
    pushbackCoords: { x: 710, y: 305 },
  },
  {
    id: 'B8',
    concourse: 'B',
    terminal: 'T2',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'AVAILABLE',
    hasDualJetbridge: true,
    coordinates: { x: 770, y: 340, angle: 90 },
    pushbackCoords: { x: 770, y: 305 },
  },

  // Concourse C (Gates C1 - C6)
  {
    id: 'C1',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'OCCUPIED',
    hasDualJetbridge: false,
    coordinates: { x: 410, y: 430, angle: 90 },
    pushbackCoords: { x: 410, y: 460 },
  },
  {
    id: 'C2',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 470, y: 430, angle: 90 },
    pushbackCoords: { x: 470, y: 460 },
  },
  {
    id: 'C3',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 530, y: 430, angle: 90 },
    pushbackCoords: { x: 530, y: 460 },
  },
  {
    id: 'C4',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'C',
    allowedCategories: ['C'],
    status: 'AVAILABLE',
    hasDualJetbridge: false,
    coordinates: { x: 590, y: 430, angle: 90 },
    pushbackCoords: { x: 590, y: 460 },
  },
  {
    id: 'C5',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'D',
    allowedCategories: ['C', 'D'],
    status: 'AVAILABLE',
    hasDualJetbridge: true,
    coordinates: { x: 660, y: 430, angle: 90 },
    pushbackCoords: { x: 660, y: 465 },
  },
  {
    id: 'C6',
    concourse: 'C',
    terminal: 'T2',
    maxCategory: 'E',
    allowedCategories: ['C', 'D', 'E'],
    status: 'AVAILABLE',
    hasDualJetbridge: true,
    coordinates: { x: 730, y: 430, angle: 90 },
    pushbackCoords: { x: 730, y: 465 },
  },
];

export const INITIAL_WEATHER: WeatherState = {
  condition: 'CLEAR',
  windSpeedKnots: 11,
  windDirectionDeg: 80,
  visibilitySm: 10,
  qnh: 1013,
  metarRaw: 'KDEN 122115Z 08011KT 10SM FEW050 SCT220 22/09 A2992 RMK AO2 SLP113',
  crosswindComponent: 2,
  aarReductionPercent: 0,
};

export const INITIAL_VEHICLES: GroundVehicle[] = [
  {
    id: 'TUG-01',
    callsign: 'P-TUG 01',
    type: 'PUSHBACK_TRACTOR',
    status: 'SERVICING',
    assignedGateId: 'A4',
    assignedFlightId: 'f-ua442',
    position: { x: 540, y: 226, heading: 0 },
    speed: 5,
    batteryFuelPercent: 94,
  },
  {
    id: 'TUG-02',
    callsign: 'P-TUG 02',
    type: 'PUSHBACK_TRACTOR',
    status: 'IDLE',
    assignedGateId: undefined,
    position: { x: 360, y: 310, heading: 90 },
    speed: 0,
    batteryFuelPercent: 88,
  },
  {
    id: 'FUEL-10',
    callsign: 'BOWSER 10',
    type: 'FUEL_BOWSER',
    status: 'SERVICING',
    assignedGateId: 'A7',
    assignedFlightId: 'f-ba219',
    position: { x: 712, y: 254, heading: 45 },
    speed: 0,
    batteryFuelPercent: 78,
  },
  {
    id: 'FUEL-11',
    callsign: 'BOWSER 11',
    type: 'FUEL_BOWSER',
    status: 'DISPATCHED',
    assignedGateId: 'B6',
    assignedFlightId: 'f-lh438',
    position: { x: 610, y: 315, heading: 90 },
    speed: 12,
    batteryFuelPercent: 82,
  },
  {
    id: 'BAG-21',
    callsign: 'BAG TUG 21',
    type: 'BAGGAGE_TUG',
    status: 'SERVICING',
    assignedGateId: 'B2',
    assignedFlightId: 'f-dl109',
    position: { x: 448, y: 345, heading: 180 },
    speed: 0,
    batteryFuelPercent: 91,
  },
  {
    id: 'BAG-22',
    callsign: 'BAG TUG 22',
    type: 'BAGGAGE_TUG',
    status: 'DISPATCHED',
    assignedGateId: 'A6',
    assignedFlightId: 'f-wn834',
    position: { x: 620, y: 228, heading: 90 },
    speed: 14,
    batteryFuelPercent: 69,
  },
  {
    id: 'CAT-31',
    callsign: 'CATER 31',
    type: 'CATERING_TRUCK',
    status: 'SERVICING',
    assignedGateId: 'B6',
    assignedFlightId: 'f-lh438',
    position: { x: 658, y: 334, heading: 270 },
    speed: 0,
    batteryFuelPercent: 85,
  },
  {
    id: 'MARSHAL-1',
    callsign: 'OPS-1 LEADER',
    type: 'FOLLOW_ME',
    status: 'IDLE',
    assignedGateId: undefined,
    position: { x: 310, y: 220, heading: 90 },
    speed: 0,
    batteryFuelPercent: 98,
  },
];

// Helper to create milestone history
function createMilestones(baseTime: number, isArrival: boolean, delayMin: number) {
  if (isArrival) {
    return [
      { id: 'm1', name: 'Descent (FL100)', targetTime: baseTime - 25, actualTime: baseTime - 25 + delayMin, completed: true, varianceMin: delayMin },
      { id: 'm2', name: 'Final Approach', targetTime: baseTime - 8, actualTime: baseTime - 8 + delayMin, completed: delayMin < 30, varianceMin: delayMin },
      { id: 'm3', name: 'Touchdown', targetTime: baseTime, actualTime: delayMin === 0 ? baseTime : undefined, completed: delayMin === 0, varianceMin: delayMin },
      { id: 'm4', name: 'Runway Vacate', targetTime: baseTime + 3, completed: false, varianceMin: delayMin },
      { id: 'm5', name: 'Taxi to Gate', targetTime: baseTime + 8, completed: false, varianceMin: delayMin },
      { id: 'm6', name: 'Chocks On Gate', targetTime: baseTime + 12, completed: false, varianceMin: delayMin },
    ];
  } else {
    return [
      { id: 'm1', name: 'Crew & Fuel Chk', targetTime: baseTime - 50, actualTime: baseTime - 50, completed: true, varianceMin: 0 },
      { id: 'm2', name: 'Boarding Start', targetTime: baseTime - 35, actualTime: baseTime - 35 + delayMin, completed: true, varianceMin: delayMin },
      { id: 'm3', name: 'Doors Closed', targetTime: baseTime - 10, actualTime: baseTime - 10 + delayMin, completed: delayMin < 20, varianceMin: delayMin },
      { id: 'm4', name: 'Pushback Clear', targetTime: baseTime, completed: false, varianceMin: delayMin },
      { id: 'm5', name: 'Taxi Out RWY', targetTime: baseTime + 10, completed: false, varianceMin: delayMin },
      { id: 'm6', name: 'Airborne Takeoff', targetTime: baseTime + 18, completed: false, varianceMin: delayMin },
    ];
  }
}

/**
 * Initial Flight Dataset: Simulation clock starts at 14:15 Z (855 minutes from 00:00)
 */
export const INITIAL_SIM_TIME = 855; // 14:15Z

export const INITIAL_FLIGHTS: Flight[] = [
  // 1. British Airways 219 (LHR -> KDEN) Heavy B787-9 Wide-body, At Gate A7
  {
    id: 'f-ba219',
    flightNumber: 'BA219',
    callsign: 'SPEEDBIRD 219',
    airline: { code: 'BA', name: 'British Airways', color: '#01295C', textColor: '#ffffff' },
    origin: 'EGLL (LHR)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 787-9 Dreamliner',
    category: 'E',
    passengers: 238,
    status: 'AT_GATE',
    scheduledTime: 820, // 13:40Z
    estimatedTime: 825, // 13:45Z
    actualTime: 824,
    gateOccupancyStart: 826,
    gateOccupancyEnd: 910, // 15:10Z
    assignedGateId: 'A7',
    assignedRunwayId: '09L/27R',
    delayMinutes: 4,
    delayHistory: [
      { code: 'WND', message: 'Headwinds over Oceanic Track Charlie', timestamp: 790, source: 'Oceanic ATC', minutesAdded: 4 },
    ],
    milestones: createMilestones(820, true, 4),
    position: { x: 700, y: 250, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 2. United Airlines 442 (KDEN -> ORD) B737-MAX9 Narrow-body, At Gate A4, Boarding / Pushback prep
  {
    id: 'f-ua442',
    flightNumber: 'UA442',
    callsign: 'UNITED 442',
    airline: { code: 'UA', name: 'United Airlines', color: '#005DAA', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'KORD (Chicago)',
    isArrival: false,
    aircraftType: 'Boeing 737-MAX9',
    category: 'C',
    passengers: 178,
    status: 'BOARDING',
    scheduledTime: 865, // 14:25Z
    estimatedTime: 875, // 14:35Z
    gateOccupancyStart: 800,
    gateOccupancyEnd: 875,
    assignedGateId: 'A4',
    assignedRunwayId: '09L/27R',
    delayMinutes: 10,
    delayHistory: [
      { code: 'BAG', message: 'Late connecting transfer baggage from inbound flight UA112', timestamp: 840, source: 'Ramp Operations', minutesAdded: 10 },
    ],
    milestones: createMilestones(865, false, 10),
    position: { x: 540, y: 250, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 3. Southwest 834 (PHX -> KDEN) B737-700, At Gate A6
  {
    id: 'f-wn834',
    flightNumber: 'WN834',
    callsign: 'SOUTHWEST 834',
    airline: { code: 'WN', name: 'Southwest Airlines', color: '#304CB2', textColor: '#ffffff' },
    origin: 'KPHX (Phoenix)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 737-700',
    category: 'C',
    passengers: 143,
    status: 'AT_GATE',
    scheduledTime: 840, // 14:00Z
    estimatedTime: 842,
    actualTime: 841,
    gateOccupancyStart: 845,
    gateOccupancyEnd: 895, // 14:55Z
    assignedGateId: 'A6',
    assignedRunwayId: '09L/27R',
    delayMinutes: 1,
    delayHistory: [],
    milestones: createMilestones(840, true, 1),
    position: { x: 640, y: 250, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 4. Delta 109 (ATL -> KDEN) A321neo Narrow-body, At Gate B2
  {
    id: 'f-dl109',
    flightNumber: 'DL109',
    callsign: 'DELTA 109',
    airline: { code: 'DL', name: 'Delta Air Lines', color: '#861F41', textColor: '#ffffff' },
    origin: 'KATL (Atlanta)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A321neo',
    category: 'C',
    passengers: 194,
    status: 'AT_GATE',
    scheduledTime: 835,
    estimatedTime: 835,
    actualTime: 836,
    gateOccupancyStart: 840,
    gateOccupancyEnd: 890,
    assignedGateId: 'B2',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(835, true, 0),
    position: { x: 440, y: 340, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 5. Lufthansa 438 (EDDF / FRA -> KDEN) A350-900 Heavy Wide-body, At Gate B6 (Dual Jetbridge)
  {
    id: 'f-lh438',
    flightNumber: 'LH438',
    callsign: 'LUFTHANSA 438',
    airline: { code: 'LH', name: 'Lufthansa', color: '#FFAC00', textColor: '#05164D' },
    origin: 'EDDF (Frankfurt)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A350-900',
    category: 'E',
    passengers: 293,
    status: 'AT_GATE',
    scheduledTime: 830,
    estimatedTime: 830,
    actualTime: 829,
    gateOccupancyStart: 835,
    gateOccupancyEnd: 920,
    assignedGateId: 'B6',
    assignedRunwayId: '09L/27R',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(830, true, 0),
    position: { x: 650, y: 340, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 6. American Airlines 1844 (DFW -> KDEN) A320, At Gate B5
  {
    id: 'f-aa1844',
    flightNumber: 'AA1844',
    callsign: 'AMERICAN 1844',
    airline: { code: 'AA', name: 'American Airlines', color: '#0078D2', textColor: '#ffffff' },
    origin: 'KDFW (Dallas)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A320',
    category: 'C',
    passengers: 150,
    status: 'AT_GATE',
    scheduledTime: 845,
    estimatedTime: 845,
    actualTime: 846,
    gateOccupancyStart: 850,
    gateOccupancyEnd: 900,
    assignedGateId: 'B5',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(845, true, 0),
    position: { x: 590, y: 340, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 7. Alaska Airlines 672 (SEA -> KDEN) B737-900ER, At Gate C1
  {
    id: 'f-as672',
    flightNumber: 'AS672',
    callsign: 'ALASKA 672',
    airline: { code: 'AS', name: 'Alaska Airlines', color: '#01426A', textColor: '#ffffff' },
    origin: 'KSEA (Seattle)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 737-900ER',
    category: 'C',
    passengers: 178,
    status: 'AT_GATE',
    scheduledTime: 850,
    estimatedTime: 850,
    gateOccupancyStart: 852,
    gateOccupancyEnd: 905,
    assignedGateId: 'C1',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(850, true, 0),
    position: { x: 410, y: 430, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 8. United Airlines 2110 (KDEN -> SFO) B777-200ER (Code E Heavy), Scheduled for Gate B7
  {
    id: 'f-ua2110',
    flightNumber: 'UA2110',
    callsign: 'UNITED 2110',
    airline: { code: 'UA', name: 'United Airlines', color: '#005DAA', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'KSFO (San Francisco)',
    isArrival: false,
    aircraftType: 'Boeing 777-200ER',
    category: 'E',
    passengers: 276,
    status: 'SCHEDULED',
    scheduledTime: 915, // 15:15Z
    estimatedTime: 915,
    gateOccupancyStart: 870,
    gateOccupancyEnd: 925,
    assignedGateId: 'B7',
    assignedRunwayId: '09L/27R',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(915, false, 0),
    position: { x: 710, y: 340, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 9. Delta 882 (KDEN -> LGA) A220-300, Taxiing Out towards RWY 09L via Taxiway Alpha
  {
    id: 'f-dl882',
    flightNumber: 'DL882',
    callsign: 'DELTA 882',
    airline: { code: 'DL', name: 'Delta Air Lines', color: '#861F41', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'KLGA (New York)',
    isArrival: false,
    aircraftType: 'Airbus A220-300',
    category: 'C',
    passengers: 130,
    status: 'TAXI_OUT',
    scheduledTime: 850,
    estimatedTime: 855,
    gateOccupancyStart: 800,
    gateOccupancyEnd: 850,
    assignedGateId: 'A2',
    assignedRunwayId: '09L/27R',
    delayMinutes: 5,
    delayHistory: [
      { code: 'ATC', message: 'Ground meter hold for runway sequence', timestamp: 850, source: 'Tower Ground', minutesAdded: 5 },
    ],
    milestones: createMilestones(850, false, 5),
    position: { x: 260, y: 175, altitude: 0, speed: 14, heading: 90, stage: 'TAXIWAY' },
  },

  // 10. Emirates 241 (OMDB / DXB -> KDEN) B777-300ER Heavy, Inbound on Final Approach to RWY 09L!
  {
    id: 'f-ek241',
    flightNumber: 'EK241',
    callsign: 'EMIRATES 241',
    airline: { code: 'EK', name: 'Emirates', color: '#D71921', textColor: '#ffffff' },
    origin: 'OMDB (Dubai)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 777-300ER',
    category: 'E',
    passengers: 354,
    status: 'FINAL',
    scheduledTime: 858, // 14:18Z
    estimatedTime: 858,
    gateOccupancyStart: 866,
    gateOccupancyEnd: 955,
    assignedGateId: 'A8', // Code E gate
    assignedRunwayId: '09L/27R',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(858, true, 0),
    position: { x: 40, y: 130, altitude: 450, speed: 148, heading: 90, stage: 'FINAL' },
  },

  // 11. Air France 026 (LFPG / CDG -> KDEN) A350-900, On Approach Corridor 12 miles out
  {
    id: 'f-af026',
    flightNumber: 'AF026',
    callsign: 'AIRFRANCE 026',
    airline: { code: 'AF', name: 'Air France', color: '#002157', textColor: '#ffffff' },
    origin: 'LFPG (Paris CDG)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A350-900',
    category: 'E',
    passengers: 282,
    status: 'ON_APPROACH',
    scheduledTime: 868, // 14:28Z
    estimatedTime: 870,
    gateOccupancyStart: 880,
    gateOccupancyEnd: 960,
    assignedGateId: 'B8', // Code E gate
    assignedRunwayId: '09L/27R',
    delayMinutes: 2,
    delayHistory: [],
    milestones: createMilestones(868, true, 2),
    position: { x: -80, y: 130, altitude: 2800, speed: 195, heading: 90, stage: 'AIR' },
  },

  // 12. JetBlue 554 (BOS -> KDEN) A321LR, Approaching RWY 09R
  {
    id: 'f-b6554',
    flightNumber: 'B6554',
    callsign: 'JETBLUE 554',
    airline: { code: 'B6', name: 'JetBlue Airways', color: '#003876', textColor: '#ffffff' },
    origin: 'KBOS (Boston)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A321LR',
    category: 'C',
    passengers: 162,
    status: 'ON_APPROACH',
    scheduledTime: 862, // 14:22Z
    estimatedTime: 863,
    gateOccupancyStart: 870,
    gateOccupancyEnd: 915,
    assignedGateId: 'C3',
    assignedRunwayId: '09R/27L',
    delayMinutes: 1,
    delayHistory: [],
    milestones: createMilestones(862, true, 1),
    position: { x: -30, y: 530, altitude: 1200, speed: 165, heading: 90, stage: 'AIR' },
  },

  // 13. United Airlines 718 (LAX -> KDEN) B787-8, En Route Inbound
  {
    id: 'f-ua718',
    flightNumber: 'UA718',
    callsign: 'UNITED 718',
    airline: { code: 'UA', name: 'United Airlines', color: '#005DAA', textColor: '#ffffff' },
    origin: 'KLAX (Los Angeles)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 787-8',
    category: 'E',
    passengers: 243,
    status: 'EN_ROUTE',
    scheduledTime: 885, // 14:45Z
    estimatedTime: 885,
    gateOccupancyStart: 895,
    gateOccupancyEnd: 975,
    assignedGateId: 'C6', // Code E gate
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(885, true, 0),
    position: { x: -180, y: 490, altitude: 6500, speed: 280, heading: 85, stage: 'AIR' },
  },

  // 14. American Airlines 2490 (KDEN -> MIA) B737-800, Scheduled Gate C2
  {
    id: 'f-aa2490',
    flightNumber: 'AA2490',
    callsign: 'AMERICAN 2490',
    airline: { code: 'AA', name: 'American Airlines', color: '#0078D2', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'KMIA (Miami)',
    isArrival: false,
    aircraftType: 'Boeing 737-800',
    category: 'C',
    passengers: 160,
    status: 'SCHEDULED',
    scheduledTime: 920,
    estimatedTime: 920,
    gateOccupancyStart: 875,
    gateOccupancyEnd: 930,
    assignedGateId: 'C2',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(920, false, 0),
    position: { x: 470, y: 430, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 15. Southwest 1902 (MDW -> KDEN) B737-800, Scheduled Gate A5
  {
    id: 'f-wn1902',
    flightNumber: 'WN1902',
    callsign: 'SOUTHWEST 1902',
    airline: { code: 'WN', name: 'Southwest Airlines', color: '#304CB2', textColor: '#ffffff' },
    origin: 'KMDW (Chicago Midway)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 737-800',
    category: 'C',
    passengers: 175,
    status: 'EN_ROUTE',
    scheduledTime: 890,
    estimatedTime: 895,
    gateOccupancyStart: 902,
    gateOccupancyEnd: 945,
    assignedGateId: 'A5',
    assignedRunwayId: '09L/27R',
    delayMinutes: 5,
    delayHistory: [],
    milestones: createMilestones(890, true, 5),
    position: { x: -220, y: 160, altitude: 7200, speed: 290, heading: 92, stage: 'AIR' },
  },

  // 16. Singapore Airlines 38 (WSSS / SIN -> KDEN via NRT) A350-900ULR, Scheduled Gate A7 after BA219
  {
    id: 'f-sq038',
    flightNumber: 'SQ038',
    callsign: 'SINGAPORE 38',
    airline: { code: 'SQ', name: 'Singapore Airlines', color: '#F8AC1C', textColor: '#021844' },
    origin: 'WSSS (Singapore)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A350-900',
    category: 'E',
    passengers: 161,
    status: 'EN_ROUTE',
    scheduledTime: 925,
    estimatedTime: 930,
    gateOccupancyStart: 938,
    gateOccupancyEnd: 1020,
    assignedGateId: 'A7', // Note: BA219 ends at 910; 28 min buffer >= 15 min buffer!
    assignedRunwayId: '09L/27R',
    delayMinutes: 5,
    delayHistory: [],
    milestones: createMilestones(925, true, 5),
    position: { x: -350, y: 110, altitude: 9400, speed: 310, heading: 90, stage: 'AIR' },
  },

  // 17. United Airlines 329 (KDEN -> IAH) A319, Taxiing In from RWY 09R after early arrival
  {
    id: 'f-ua329',
    flightNumber: 'UA329',
    callsign: 'UNITED 329',
    airline: { code: 'UA', name: 'United Airlines', color: '#005DAA', textColor: '#ffffff' },
    origin: 'KIAH (Houston)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Airbus A319',
    category: 'C',
    passengers: 128,
    status: 'TAXI_IN',
    scheduledTime: 852,
    estimatedTime: 852,
    actualTime: 851,
    gateOccupancyStart: 858,
    gateOccupancyEnd: 910,
    assignedGateId: 'B3',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(852, true, 0),
    position: { x: 500, y: 480, altitude: 0, speed: 16, heading: 0, stage: 'TAXIWAY' },
  },

  // 18. British Airways 218 (KDEN -> EGLL / LHR) B787-9 Turnaround of BA219, Departure
  {
    id: 'f-ba218',
    flightNumber: 'BA218',
    callsign: 'SPEEDBIRD 218',
    airline: { code: 'BA', name: 'British Airways', color: '#01295C', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'EGLL (London Heathrow)',
    isArrival: false,
    aircraftType: 'Boeing 787-9 Dreamliner',
    category: 'E',
    passengers: 235,
    status: 'SCHEDULED',
    scheduledTime: 960, // 16:00Z
    estimatedTime: 960,
    gateOccupancyStart: 900,
    gateOccupancyEnd: 965,
    assignedGateId: 'A8',
    assignedRunwayId: '09L/27R',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(960, false, 0),
    position: { x: 760, y: 250, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },

  // 19. FedEx 1402 (MEM -> KDEN) B767-300F Cargo (Code D), Inbound Cargo Ramp
  {
    id: 'f-fx1402',
    flightNumber: 'FDX1402',
    callsign: 'FEDEX 1402',
    airline: { code: 'FX', name: 'FedEx Express', color: '#4D148C', textColor: '#ffffff' },
    origin: 'KMEM (Memphis)',
    destination: 'KDEN',
    isArrival: true,
    aircraftType: 'Boeing 767-300F',
    category: 'D',
    passengers: 2,
    status: 'ON_APPROACH',
    scheduledTime: 872,
    estimatedTime: 872,
    gateOccupancyStart: 885,
    gateOccupancyEnd: 960,
    assignedGateId: 'C5', // Code D gate
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(872, true, 0),
    position: { x: -110, y: 530, altitude: 2400, speed: 175, heading: 90, stage: 'AIR' },
  },

  // 20. Delta 1774 (KDEN -> MSP) A321, Scheduled for Gate B1
  {
    id: 'f-dl1774',
    flightNumber: 'DL1774',
    callsign: 'DELTA 1774',
    airline: { code: 'DL', name: 'Delta Air Lines', color: '#861F41', textColor: '#ffffff' },
    origin: 'KDEN',
    destination: 'KMSP (Minneapolis)',
    isArrival: false,
    aircraftType: 'Airbus A321',
    category: 'C',
    passengers: 188,
    status: 'SCHEDULED',
    scheduledTime: 930,
    estimatedTime: 930,
    gateOccupancyStart: 885,
    gateOccupancyEnd: 935,
    assignedGateId: 'B1',
    assignedRunwayId: '09R/27L',
    delayMinutes: 0,
    delayHistory: [],
    milestones: createMilestones(930, false, 0),
    position: { x: 390, y: 340, altitude: 0, speed: 0, heading: 90, stage: 'GATE' },
  },
];
